version: "3.9"
services:
  api:
    build: .
    environment:
      GITHUB_APP_ID: ${GITHUB_APP_ID}
      GITHUB_APP_PRIVATE_KEY: ${GITHUB_APP_PRIVATE_KEY}
      GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET}
      DATABASE_URL: postgres://postgres:postgres@db:5432/agent
      REDIS_URL: redis://redis:6379
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LOG_LEVEL: info
    ports:
      - "3000:3000"
    depends_on: [db, redis, worker]
  worker:
    build: .
    command: ["node","dist/worker.js"]
    environment:
      GITHUB_APP_ID: ${GITHUB_APP_ID}
      GITHUB_APP_PRIVATE_KEY: ${GITHUB_APP_PRIVATE_KEY}
      GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET}
      DATABASE_URL: postgres://postgres:postgres@db:5432/agent
      REDIS_URL: redis://redis:6379
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LOG_LEVEL: info
    depends_on: [db, redis]
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agent
    ports: ["5433:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
